version: 2.2

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Build step"
          command: dotnet publish -c Release -r win10-x64
      - run:
          name: "Run Tests"
          command: dotnet test Tests/Tests.csproj -v n
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.2\win10-x64\publish\